#!/bin/bash

if [ $# -lt 2 ]; then
    echo "please give at least 2 parameters: project and target_hosts. eg. deploy static staging(test, or prd)"
    exit 1
fi

git_branch="HEAD"
if [[ $# -ge 3 ]]; then
  git_branch=$3
fi

if [ -L $0 ] ; then
    WORKING_PATH=$(cd `dirname $(readlink -f $0)`; pwd);
else
    WORKING_PATH=$(cd `dirname ${0}`; pwd);
fi;

cd $WORKING_PATH
case "$1" in
  simpleweb)
      if [[ $# -ge 3 ]]; then
        ansible-playbook -i config/webapp.hosts simpleweb.yml --extra-vars "target_hosts=$2" -e "git_branch=$3"
        exit
      fi
        ansible-playbook -i config/webapp.hosts simpleweb.yml --extra-vars "target_hosts=$2"
      ;;

  static-test)
      if [[ $# -ge 3 ]]; then
        ansible-playbook -i config/static.hosts static.yml --extra-vars "target_hosts=$2"  -e "git_branch=$3"
        exit
      fi
        ansible-playbook -i config/static.hosts static.yml --extra-vars "target_hosts=$2"
      ;;
esac
