#!/bin/bash
set -o pipefail
if [ $# -lt 2 ]; then
    echo "please give at least 2 parameters: project and target_hosts. eg. deploy static staging(test, or prd) feature/newfeature"
    exit 1
fi

git_branch="HEAD"
if [[ $# -ge 3 ]]; then
  git_branch=$3
fi

if [ -L $0 ] ; then
    WORKING_PATH=$(cd `dirname $(readlink -f $0)`; pwd);
else
    WORKING_PATH=$(cd `dirname ${0}`; pwd);
fi;

cd $WORKING_PATH

dist_path=~/tw-interview/WebApp/dist/
static_path=~/tw-interview/static-test/
simpleweb_path=~/tw-interview/simpleweb/


case "$1" in
  setup)
      echo "downloading web service and java environment"

      docker pull tomcat:jdk8-corretto
      docker pull weiwei100/ansible:v1
      cd ../
      git clone https://github.com/acehoe/static-test.git
      git clone https://github.com/acehoe/simpleweb.git

      docker run -it --rm -p 8082:8080 -v $dist_path:/usr/local/tomcat/webapps/ -v $static_path:/usr/local/tomcat/webapps/static -v $simpleweb_path:/usr/local/tomcat/source tomcat:jdk8-corretto
      echo "setting up done..."

      ;;

  build)
      cid=`docker ps|grep "tomcat:jdk8-corretto" |awk '{print $1}'`
      echo "compliling and packaging"
      docker exec $cid javac source/web/Simple.java
      docker exec $cid jar cvf webapps/WebApp.war -C source/web .
      echo "done build, you are ready to check your site"
      ;;

  simpleweb)
          docker run -ti --rm ansible:v1 bash tw-interview/deploy $1 $2 $3
          ;;
  static-test)
        docker run -ti --rm ansible:v1 bash tw-interview/deploy $1 $2 $3
      ;;
esac
